version: "3"
services:
    web:
        build:
            context: .
            dockerfile: webapi.dockerfile
        ports:
            - "8000:5000"
        depends_on:
            - db
        container_name: webapi-server
        networks:
            - webapi-network
    db:
        image: "microsoft/mssql-server-linux"
        container_name: webapi-database
        environment:
            SA_PASSWORD: "p@ssw0rd"
            ACCEPT_EULA: "Y"
        restart: always
        networks:
            - webapi-network
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: webapi-nginx
        ports:
            - "5010:80"
        links:
            - web
        networks:
            - webapi-network
networks:
    webapi-network:
        driver: bridge